runtime: python311

env_variables:
  REDIS_HOST: "your-redis-host"
  REDIS_PORT: "6379"
  PORT: "8080"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

handlers:
- url: /.*
  script: auto
  secure: always
